
<h1 align="center"> Battle of the Neighbourhoods - Toronto </h1>

***
> **Author: Mika Raymond Adrian Batubara**
***

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns',None)

##  QUESTION 1

In [2]:
import requests

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
wiki_url = requests.get(url)
wiki_url

In [13]:
data = pd.read_html(wiki_url.text)
data

[    Postal Code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 ..          ...               ...
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                          Neighbourhood
 0                                         Not assigned
 1                                         Not assigned
 2                                            Parkwoods
 3                                     Victoria Village
 4                            Regent Park, Harbourfront
 ..                                                 ...
 175                                       Not assigned
 176                                       Not assigned
 177                                       Not assigned
 178  Mimico NW, The Queensway West, South of Bloor,...
 179                                       Not assigned

 [180 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

In [14]:
type(data)

list

In [15]:
data = data[0]
data

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

## TASK

3. To create the above dataframe:

- The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
- Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.
- More than one neighborhood can exist in one postal code area. For example, in the table on the Wikipedia page, you will notice that M5A is listed twice and has two neighborhoods: Harbourfront and Regent Park. These two rows will be combined into one row with the neighborhoods separated with a comma as shown in row 11  in the above table.-
- If a cell has a borough but a Not assigned  neighborhood, then the neighborhood will be the same as the borough.
- Clean your Notebook and add Markdown cells to explain your work and any assumptions you are making.
- In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.

In [16]:
type(data)

pandas.core.frame.DataFrame

**IGNORE CELLS with a borough that is Not Assigned**

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Postal Code    180 non-null    object
 1   Borough        180 non-null    object
 2   Neighbourhood  180 non-null    object
dtypes: object(3)
memory usage: 4.3+ KB

In [17]:
data[data['Borough']=='Not assigned']

    Postal Code       Borough Neighbourhood
0           M1A  Not assigned  Not assigned
1           M2A  Not assigned  Not assigned
7           M8A  Not assigned  Not assigned
10          M2B  Not assigned  Not assigned
15          M7B  Not assigned  Not assigned
16          M8B  Not assigned  Not assigned
19          M2C  Not assigned  Not assigned
24          M7C  Not assigned  Not assigned
25          M8C  Not assigned  Not assigned
28          M2E  Not assigned  Not assigned
29          M3E  Not assigned  Not assigned
33          M7E  Not assigned  Not assigned
34          M8E  Not assigned  Not assigned
35          M9E  Not assigned  Not assigned
37          M2G  Not assigned  Not assigned
38          M3G  Not assigned  Not assigned
42          M7G  Not assigned  Not assigned
43          M8G  Not assigned  Not assigned
44          M9G  Not assigned  Not assigned
51          M7H  Not assigned  Not assigned
52          M8H  Not assigned  Not assigned
53          M9H  Not assigned  Not assigned
60          M7J  Not assigned  Not assigned
61          M8J  Not assigned  Not assigned
62          M9J  Not assigned  Not assigned
69          M7K  Not assigned  Not assigned
70          M8K  Not assigned  Not assigned
71          M9K  Not assigned  Not assigned
78          M7L  Not assigned  Not assigned
79          M8L  Not assigned  Not assigned
87          M7M  Not assigned  Not assigned
88          M8M  Not assigned  Not assigned
96          M7N  Not assigned  Not assigned
97          M8N  Not assigned  Not assigned
101         M3P  Not assigned  Not assigned
105         M7P  Not assigned  Not assigned
106         M8P  Not assigned  Not assigned
110         M3R  Not assigned  Not assigned
115         M8R  Not assigned  Not assigned
118         M2S  Not assigned  Not assigned
119         M3S  Not assigned  Not assigned
123         M7S  Not assigned  Not assigned
124         M8S  Not assigned  Not assigned
125         M9S  Not assigned  Not assigned
127         M2T  Not assigned  Not assigned
128         M3T  Not assigned  Not assigned
131         M6T  Not assigned  Not assigned
132         M7T  Not assigned  Not assigned
133         M8T  Not assigned  Not assigned
134         M9T  Not assigned  Not assigned
136         M2V  Not assigned  Not assigned
137         M3V  Not assigned  Not assigned
140         M6V  Not assigned  Not assigned
141         M7V  Not assigned  Not assigned
145         M2W  Not assigned  Not assigned
146         M3W  Not assigned  Not assigned
149         M6W  Not assigned  Not assigned
150         M7W  Not assigned  Not assigned
154         M2X  Not assigned  Not assigned
155         M3X  Not assigned  Not assigned
158         M6X  Not assigned  Not assigned
159         M7X  Not assigned  Not assigned
161         M9X  Not assigned  Not assigned
162         M1Y  Not assigned  Not assigned
163         M2Y  Not assigned  Not assigned
164         M3Y  Not assigned  Not assigned
166         M5Y  Not assigned  Not assigned
167         M6Y  Not assigned  Not assigned
170         M9Y  Not assigned  Not assigned
171         M1Z  Not assigned  Not assigned
172         M2Z  Not assigned  Not assigned
173         M3Z  Not assigned  Not assigned
174         M4Z  Not assigned  Not assigned
175         M5Z  Not assigned  Not assigned
176         M6Z  Not assigned  Not assigned
177         M7Z  Not assigned  Not assigned
179         M9Z  Not assigned  Not assigned

In [19]:
data = data[data['Borough']!= 'Not assigned']

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103 entries, 2 to 178
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Postal Code    103 non-null    object
 1   Borough        103 non-null    object
 2   Neighbourhood  103 non-null    object
dtypes: object(3)
memory usage: 3.2+ KB

In [24]:
df = data.groupby(['Postal Code']).head()
df

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [26]:
data['Postal Code'].nunique()

103

In [34]:
data.Neighbourhood.str.count("Not assigned").sum()

0

In [35]:
data.shape

(103, 3)